version: '3.9'

services:
  php:
    build: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html/
    restart: unless-stopped
  phpunit:
    image: php:8.2-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpunit
  composer:
    image: composer:1.9.3
    environment:
      - COMPOSER_CACHE_DIR=/app/.cache/composer
    volumes:
      - .:/app
    restart: never
  phpcli:
    image: php:8.2-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
  phpstan:
    image: php:8.2-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: vendor/bin/phpstan